# These are supported funding model platforms
ko_fi: thierrymarianne # Replace with a single Ko-fi username
liberapay: thierrymarianne
custom: https://www.buymeacoffee.com/thierrymarianne
github: [thierrymarianne]
#patreon: # Replace with a single Patreon username
#issuehunt: # Replace with a single IssueHunt username
#otechie: # Replace with a single Otechie username
#lfx_crowdfunding: # Replace with a single LFX Crowdfunding project-name e.g., cloud-foundry
