services:

  app:
    build:
      context:    '../../'
      dockerfile: './provisioning/containers/worker/Dockerfile'
      platforms:
        - linux/x86_64
    env_file:
      - '../../.env'
    restart:      'always'
    volumes:
      - './_scripts/:/scripts'
      - '../../../shared/:/var/www/shared'

  worker:
    build:
      context:    '../../'
      dockerfile: './provisioning/containers/worker/Dockerfile'
      platforms:
        - linux/x86_64
    env_file:
      - '../../.env'
    restart:      'always'
    volumes:
      - './_scripts/:/scripts'
      - '../../../shared/:/var/www/shared'
